# Generated by Django 2.0.5 on 2018-09-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='areaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('DG', 'Direccion General'), ('DA', 'Dirección Academica'), ('SDI', 'Subdirección de Investigación'), ('CINT', 'Coordinación de Intercambios'), ('CPRO', 'Coordinación de Proyectos'), ('SDD', 'Subdirección de Docencia'), ('CSE', 'Coordinación de Servicios Escolares'), ('PCDMX', 'Posgrado en la CDMX'), ('PLNGT', 'Posgrado en LINGÜÍSTICA'), ('POCCI', 'Posgrado en OCCIDENTE'), ('PSURE', 'Posgrado en SURESTE'), ('PGOLF', 'Posgrado en GOLFO'), ('PPENI', 'Posgrado en PENINSULAR'), ('PNORE', 'Posgrado en NORESTE'), ('SDB', 'Subdirección de Bibliotecas'), ('SDDP', 'Subdirección de Difusión y Publicaciones'), ('CPUB', 'Coordinación de Publicaciones'), ('CDIF', 'Coordinación de difusión'), ('SDINF', 'Subdirección de Informática'), ('CSIS', 'Coordinación de Sistemas'), ('DV', 'Dirección de Vinculación'), ('DADMN', 'Dirección de Administración'), ('CPLYC', 'Coordinación de Planeación y Control'), ('UTRNS', 'Unidad de Trasparencia'), ('SDRH', 'Subdirección de Recursos Financieros'), ('JFPR', 'Jefatura de Presupuestos'), ('JFCO', 'Jefatura de Contabilidad'), ('JFRH', 'Jefatura de Recursos Humanos'), ('JFSG', 'Jefatura de Servicios Generales'), ('JFRM', 'Jefatura de Recursos Materiales'), ('CARC', 'Coordinación de Archivo'), ('CAFP', 'Coordinación de Admin Financiera de Proyectos'), ('UR', 'Unidades Regionales'), ('DRG', 'Dirección Regional Golfo'), ('DRPS', 'Dirección Regional Pacifico Sur\t'), ('DRS', 'Dirección General Sureste\t'), ('DRO', 'Dirección General Occidente\t'), ('DRPN', 'Dirección Regional Peninsular\t'), ('DRN', 'Dirección Regional Noreste\t'), ('JFAD', 'Jefatura de Administración'), ('JFBI', 'Jefatura de Biblioteca')], default='DG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('ext', models.IntegerField()),
                ('imagen_usuario', models.ImageField(blank=True, upload_to='profile_pics')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.areaUsuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
